### ISSUE TITLE
Getting error while running  npm start 

### ISSUE THREAD

**Issue by preetjashan0986** [scotch-io/angular2-starter-basic#1]
I have git cloned angular2-starter-basic.. but while running npm start I am getting errors. Please suggest the solution. Following is log file text:-

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ProgrameFiles\\node.exe',
1 verbose cli   'C:\\Users\\jashanpreet.kaur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.3.0
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-starter-basic@1.0.0~ prestart: angular2-starter-basic@1.0.0
6 silly lifecycle angular2-starter-basic@1.0.0~ prestart: no script for prestart, continuing
7 info lifecycle angular2-starter-basic@1.0.0~start: angular2-starter-basic@1.0.0
8 verbose lifecycle angular2-starter-basic@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-starter-basic@1.0.0~start: PATH: C:\Users\jashanpreet.kaur\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Projects\angular2forms\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\Java\jdk1.7.0\bin;D:\wamp\bin\php\php5.5.12;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\SlikSvn\bin;\C:\Program Files (x86)\PostgreSQL\9.5\bin;C:\Program Files\PostgreSQL\pg94\bin;C:\Python35;C:\Python35\Scripts;D:\ProgrameFiles\;C:\Users\jashanpreet.kaur\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
10 verbose lifecycle angular2-starter-basic@1.0.0~start: CWD: D:\Projects\angular2forms
11 silly lifecycle angular2-starter-basic@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite"' ]
12 silly lifecycle angular2-starter-basic@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-starter-basic@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-starter-basic@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jashanpreet.kaur\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jashanpreet.kaur\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-starter-basic@1.0.0
16 verbose cwd D:\Projects\angular2forms
17 error Windows_NT 6.1.7601
18 error argv "D:\\ProgrameFiles\\node.exe" "C:\\Users\\jashanpreet.kaur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.4
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error angular2-starter-basic@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
23 error Exit status 1
24 error Failed at the angular2-starter-basic@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the angular2-starter-basic package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc && concurrently "npm run tsc:w" "npm run lite"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs angular2-starter-basic
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls angular2-starter-basic
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by scarstens** [comment]
+1 on mac, similar issue, npm install && npm run start gives:

```
npm WARN angular2-starter-basic@1.0.0 No repository field.
Seths-MacBook-Pro:ng2-routing sethcarstens$ npm start run

> angular2-starter-basic@1.0.0 start /Users/sethcarstens/Sites/ng2-routing
> tsc && concurrently "npm run tsc:w" "npm run lite" "run"

node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2693: 'Map' only refers to a type, but is being used as a value here.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2693: 'Set' only refers to a type, but is being used as a value here.
node_modules/@types/core-js/index.d.ts(47,36): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(350,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(351,52): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(352,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(353,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(354,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(355,61): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(356,60): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(357,65): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(357,97): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(358,60): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(359,58): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(360,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(361,58): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(362,61): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(362,117): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(363,42): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(365,81): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(366,78): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(367,76): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(368,73): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(431,6): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/core-js/index.d.ts(464,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(465,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(467,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(468,69): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(472,40): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(474,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(494,55): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(495,45): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(511,46): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(512,43): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(627,18): error TS2304: Cannot find name 'PromiseConstructor'.
node_modules/@types/core-js/index.d.ts(642,32): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(646,39): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(646,53): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/core-js/index.d.ts(1280,34): error TS2339: Property 'for' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1284,41): error TS2339: Property 'hasInstance' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1288,48): error TS2339: Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1292,38): error TS2339: Property 'iterator' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1296,36): error TS2339: Property 'keyFor' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1300,35): error TS2339: Property 'match' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1304,37): error TS2339: Property 'replace' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1308,36): error TS2339: Property 'search' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1312,37): error TS2339: Property 'species' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1316,35): error TS2339: Property 'split' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1320,41): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1324,41): error TS2339: Property 'toStringTag' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(1328,41): error TS2339: Property 'unscopables' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2059,34): error TS2339: Property 'for' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2063,41): error TS2339: Property 'hasInstance' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2067,48): error TS2339: Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2071,38): error TS2339: Property 'iterator' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2075,36): error TS2339: Property 'keyFor' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2079,35): error TS2339: Property 'match' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2083,37): error TS2339: Property 'replace' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2087,36): error TS2339: Property 'search' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2091,37): error TS2339: Property 'species' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2095,35): error TS2339: Property 'split' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2099,41): error TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2103,41): error TS2339: Property 'toStringTag' does not exist on type 'SymbolConstructor'.
node_modules/@types/core-js/index.d.ts(2107,41): error TS2339: Property 'unscopables' does not exist on type 'SymbolConstructor'.
node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "start" "run"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-starter-basic@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" "run"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-starter-basic@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" "run"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-starter-basic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite" "run"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-starter-basic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-starter-basic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sethcarstens/Sites/ng2-routing/npm-debug.log
Seths-MacBook-Pro:ng2-routing sethcarstens$ 

```

**Comment by Safiyya** [comment]
Use `"@types/core-js": "0.9.35"` in you `package.json` and then run `npm install`. That fixed it for me.

**Comment by buildmotion** [comment]
Thanks...worked for me.

**Comment by merchant87** [comment]
Worked for me too! Thanks!

**Comment by foxfrito** [comment]
Worked for me. Thanks!

**Comment by colthreepv** [comment]
Works.. but.. why? What to follow to have this fixed permanently, this seems like duct tape on my project.

**Comment by Pfeiffer86** [comment]
I got the error in 2.4.1
new core-js version 2.5.0 worked for me
npm install core-js --save

**Comment by scookstlmo** [comment]
didn't make any difference for me

**Comment by pvcarroll** [comment]
@scookstlmo @Judgeja @iExit1337
If you're getting errors like scarstens with messages like "node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2693:", it's because your typescript compiler is targeting node_modules.  I don't think that's necessary.  You can exclude node_modules in your typescript config (tsconfig.json) by adding this line: 
"exclude": ["node_modules"]

example tsconfig.json:

> {
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
    "exclude": ["node_modules"]
}
