### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by akash-2095** [scotch-io/angular2-starter-basic#4]
So i was trying to follow the setup videos. After the typescript typings and concurrently installation when I try to run I get this error in npm debug log

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng2-start@1.0.0~prestart: ng2-start@1.0.0
6 silly lifecycle ng2-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ng2-start@1.0.0~start: ng2-start@1.0.0
8 verbose lifecycle ng2-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-start@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\akashjain\Documents\angular2\ng2-start\node_modules\.bin;C:\Users\akashjain\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\akashjain\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\akashjain\AppData\Roaming\npm;C:\Users\akashjain\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle ng2-start@1.0.0~start: CWD: C:\Users\akashjain\Documents\angular2\ng2-start
11 silly lifecycle ng2-start@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite"' ]
12 silly lifecycle ng2-start@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle ng2-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: ng2-start@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ng2-start@1.0.0
16 verbose cwd C:\Users\akashjain\Documents\angular2\ng2-start
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ng2-start@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
22 error Exit status 2
23 error Failed at the ng2-start@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng2-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng2-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by GRajaMca** [comment]
@akash-2095 did you resolved this issue ??
